name: Deploy to microservices server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy to microservices server
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            # Step 1: Add SSH Key
            - name: Add SSH Key
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  # Use the PEM Key stored in GitHub Secrets
                  ssh-private-key: ${{ secrets.EC2_KEY }}

            # Step 2: Copy Files to EC2
            - name: Copy Files to EC2
              run: |
                  scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/server/dashboard-server

            # Step 3: SSH into EC2 and Deploy
            # Update the latest code from the repository
            # Check if any relevant files have changed
            - name: SSH into EC2 and Deploy
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
                    cd /home/${{ secrets.EC2_USER }}/server/dashboard-server
                    git pull origin main

                    CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD)
                    if echo "$CHANGED_FILES" | grep -E "Dockerfile|docker-compose.yml|package.json|.dockerignore|.gitignore|tsconfig.json|cicd-workflow.yml"; then
                      echo "Changes detected in Docker-related files, rebuilding image..."
                      docker-compose down
                      docker-compose build
                      docker-compose up -d
                    else
                      echo "No changes detected in Docker-related files, starting services without rebuild."
                      docker-compose up -d --no-build
                    fi
                  EOF
